server:
  port: 9324
spring:
  application:
    name: file-server
  profiles:
    active: dev
  datasource:
    hikari:
      max-lifetime: 30000
  main:
    allow-bean-definition-overriding: true
  data:
    redis:
      repositories:
        enabled: false
  cloud:
    stream:
      bindings:
        output:
          destination: ecm
          content-type: application/json
        input:
          destination: ecm
          content-type: application/json
          group: ecm-file-g
  redis:
    timeout: PT30M
    lettuce:
      pool:
        max-active: 500
        max-wait: 2
        max-idle: 200
        min-idle: 1
    redisson:
      singleServerConfig:
        database: 2
      threads: 0
      nettyThreads: 0
      transportMode: NIO
dubbo:
  protocol:
    name: dubbo
    port: -1
  registry:
    address: spring-cloud://localhost
  cloud:
    subscribed-services: ua
self-config:
  down-file-part-max-size: 2097152
  down-file-part-max-num: 10
  down-file-connect-timeout: 3000
  down-file-read-timeout: 3000
  down-file-max-retry: 10
