spring:
  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true
  cloud:
    nacos:
      discovery:
        server-addr: 47.108.61.234:8848
  redis:
    host: 47.108.61.234
    timeout: PT30M
  datasource:
    url: jdbc:mysql://47.108.61.234:3306/file-server?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&useSSL=true
    username: ecmRoot
    password: ecmRoot.
#  security:
#    oauth2:
#      client:
#        registration:
#      resourceserver:
#        opaquetoken:
#          client-id: app
#          client-secret: app-secret
#          introspection-uri: http://localhost:9322/ua/oauth/check_token
#          github:
#            client-id: 9c4a5a9082295648aa10
#            client-secret: a330378686ba9231a564115b36486c238f5d773d