spring:
  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true
  cloud:
    nacos:
      discovery:
        server-addr: 47.108.61.234:8848
  redis:
    host: 47.108.61.234
    timeout: PT30M
    redisson:
      singleServerConfig:
        address: "redis://47.108.61.234:6379"
        database: 2
      threads: 0
      nettyThreads: 0
      transportMode: NIO

  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://47.108.61.234:3306/fs?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&useSSL=true
    username: ecmRoot
    password: ecmRoot.
#  security:
#    oauth2:
#      client:
#        registration:
#      resourceserver:
#        opaquetoken:
#          client-id: app
#          client-secret: app-secret
#          introspection-uri: http://localhost:9322/ua/oauth/check_token
#          github:
#            client-id: 9c4a5a9082295648aa10
#            client-secret: a330378686ba9231a564115b36486c238f5d773d
self-config:
  local-file-path: D:\file_local
logging:
  level:
    org.springframework.jdbc.core: debug