server:
  port: 9323
spring:
  application:
    name: ua
  profiles:
    active: dev
  datasource:
    hikari:
      max-lifetime: 30000
  main:
    allow-bean-definition-overriding: true
dubbo:
  scan:
    base-packages: org.cc.ua.server
  protocol:
    name: dubbo
    port: -1
  registry:
    address: spring-cloud://localhost
  cloud:
    subscribed-services: file-server
self-config:

#  open-verify-code-check: true