server:
  port: 9323
spring:
  application:
    name: ua
  profiles:
    active: dev
  datasource:
    hikari:
      max-lifetime: 30000
  main:
    allow-bean-definition-overriding: true
  data:
    redis:
      repositories:
        enabled: false
  cloud:
    stream:
      bindings:
        output:
          destination: ecm
          content-type: application/json
        input:
          destination: ecm
          content-type: application/json
          group: ecm-ua-g
  redis:
    timeout: PT30M
    lettuce:
      pool:
        max-active: 500
        max-wait: 2
        max-idle: 200
        min-idle: 1
    redisson:
      singleServerConfig:
        database: 2
      threads: 0
      nettyThreads: 0
      transportMode: NIO
dubbo:
  scan:
    base-packages: org.cc.ua.server
  protocol:
    name: dubbo
    port: -1
  registry:
    address: spring-cloud://localhost
  cloud:
    subscribed-services: file-server
self-config:

#  open-verify-code-check: true