spring:
  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true
  cloud:
    nacos:
      discovery:
        server-addr: 47.108.61.234:8848
  redis:
    host: 47.108.61.234
    timeout: PT30M
  datasource:
    url: jdbc:mysql://47.108.61.234:3306/ua?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&useSSL=true
    username: ecmRoot
    password: ecmRoot.
